### ISSUE TITLE
OpenGL Crash

### ISSUE THREAD

**Issue by Gilbertil** [TaroNuke/Simply-Love-NotITG-ver.-#14]
a few months ago i tried NotITG [Idk what version, i thing before of 4.20] and i can run but now i cant run it [my drivers are updated] this is weird [also it not run on fullscreen, obs problems]

[Edit of 2021/06/19/8:25PM (GMT-7): now i know that i can played 4.20 of NotITG but now not, that situation stills and idk why]

https://user-images.githubusercontent.com/84993798/122655487-bd905700-d10f-11eb-9906-e467dccfc71b.mp4

Log File:
00:00.132: NotITG v4.2.0
00:00.132: Compiled Tue Apr 20 20:51:00 2021 (build 69)
00:00.134: Log starting 2021-06-19 15:00:24
00:00.134:  
00:00.134: VFS: No patch data found
00:00.134: ======= MOUNTPOINTS =========
00:00.135: mountpoints .....  ..... /
00:00.135: mem ..... (cache) ..... /@mem/
00:00.135: oitg ..... C:/Users/PC/Desktop/NotITG/CryptPackages ..... /Packages/
00:00.135: dir ..... C:/Users/PC/Desktop/NotITG ..... /
00:00.135: =============================
00:00.135: Reading 'Data/Defaults.ini' failed: No such file or directory
00:00.156: External address: 0x8bff38
00:00.228: Loading window: win32
00:00.228: Windows 10.0 (Win10) build 19042 []
00:00.228: Memory: 2047mb total, 4095mb swap (3318mb swap avail)
/////////////////////////////////////////
00:00.262: WARNING: RegOpenKeyEx(80000002,HARDWARE\DEVICEMAP\Scsi) error (El sistema no puede encontrar el archivo especificado.)
/////////////////////////////////////////
00:00.352: Sound device 0: Altavoces (2- High Definition A, 0.0, MID 1, PID 65535 
00:00.353: Sound device 1: Altavoces (2- High Definition A, 0.0, MID 1, PID 65535 
00:00.354: AnnouncerManager::AnnouncerManager()
00:00.356: ThemeManager::SwitchThemeAndLanguage: "SIMPLY LOVE (NotITG Ver)", "english"
00:00.612: Loading "/Themes/fallback/Scripts/Serialize.lua" ...
00:00.655: Loading "/Themes/fallback/Scripts/Serialize.lua" ...
00:00.675: Loading "/Themes/fallback/Scripts/Branches.lua" ...
00:00.697: Loading "/Themes/fallback/Scripts/Colors.lua" ...
00:00.698: Loading "/Themes/fallback/Scripts/OptionsMenu.lua" ...
00:00.699: Loading "/Themes/fallback/Scripts/Serialize.lua" ...
00:00.699: Loading "/Themes/fallback/Scripts/Sprite.lua" ...
00:00.700: Loading "/Themes/fallback/Scripts/Utilities.lua" ...
00:00.701: Loading "/Themes/default/Scripts/Branches.lua" ...
00:00.726: Loading "/Themes/default/Scripts/Colors.lua" ...
00:00.727: Loading "/Themes/default/Scripts/HelpText.lua" ...
00:00.751: Loading "/Themes/default/Scripts/Legal.lua" ...
00:00.752: Loading "/Themes/default/Scripts/OptionsMenu.lua" ...
00:00.754: Loading "/Themes/default/Scripts/Other.lua" ...
00:00.756: Loading "/Themes/fallback/Scripts/Branches.lua" ...
00:00.756: Loading "/Themes/fallback/Scripts/Colors.lua" ...
00:00.757: Loading "/Themes/fallback/Scripts/OptionsMenu.lua" ...
00:00.757: Loading "/Themes/fallback/Scripts/Serialize.lua" ...
00:00.757: Loading "/Themes/fallback/Scripts/Sprite.lua" ...
00:00.758: Loading "/Themes/fallback/Scripts/Utilities.lua" ...
00:00.758: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/02 PrefsRows.lua" ...
00:00.761: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Branches.lua" ...
00:00.761: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Colors.lua" ...
00:00.791: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Mods.lua" ...
00:00.799: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Opciones Graficas.lua" ...
00:00.800: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/OptionsMenu.lua" ...
00:00.801: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Other.lua" ...
00:00.813: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Resoluciones.lua" ...
00:00.814: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Sprite.lua" ...
00:00.815: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Stitch.lua" ...
00:00.815: [Stitch] Initialized!
00:00.815: [Stitch] We are on version "Stitch 200103 dev"
00:00.841: [Loading] ./themes/SIMPLY LOVE (NotITG Ver)/config.lua
00:00.842: [Loading] ./themes/SIMPLY LOVE (NotITG Ver)/../../Data/config.lua
00:00.842: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/Theme.lua" ...
00:00.843: Loading "/Themes/SIMPLY LOVE (NotITG ver)/Scripts/UKSRT_scoring.lua" ...
/////////////////////////////////////////
00:00.858: WARNING: GetSerialNumber(): failed to acquire port.
/////////////////////////////////////////
00:00.924: Starting thread: Decode thread
00:00.925: Starting thread: Mixer thread
00:00.926: Sound driver: WaveOut
00:00.926: Starting thread: MusicThread
00:00.927: Initializing lights drivers: 
00:00.927: LightsDriver_External::LightsDriver_External()
00:00.938: Reading 'Cache/banners.cache' failed: No such file or directory
00:00.939: Attempting to load 25 songs from "Songs/Mods Boot Camp"
00:00.941: Song::LoadFromSMFile(Cache//Songs/3109907617)
00:00.965: Song::LoadFromSMFile(Cache//Songs/2010170907)
00:00.966: Song::LoadFromSMFile(Cache//Songs/3001318270)
00:00.967: Song::LoadFromSMFile(Cache//Songs/3640446607)
00:00.968: Song::LoadFromSMFile(Cache//Songs/2328301973)
00:00.969: Song::LoadFromSMFile(Cache//Songs/3187223785)
00:00.970: Song::LoadFromSMFile(Cache//Songs/1022659211)
00:00.971: Song::LoadFromSMFile(Cache//Songs/634837869)
00:00.972: Song::LoadFromSMFile(Cache//Songs/887233614)
00:00.973: Song::LoadFromSMFile(Cache//Songs/2854891770)
00:00.973: Song::LoadFromSMFile(Cache//Songs/3381793812)
00:00.974: Song::LoadFromSMFile(Cache//Songs/3413872628)
00:00.975: Song::LoadFromSMFile(Cache//Songs/2021145700)
00:00.976: Song::LoadFromSMFile(Cache//Songs/2413482066)
00:00.977: Song::LoadFromSMFile(Cache//Songs/2434684966)
00:00.978: Song::LoadFromSMFile(Cache//Songs/4045201490)
00:00.979: Song::LoadFromSMFile(Cache//Songs/4204841871)
00:00.980: Song::LoadFromSMFile(Cache//Songs/3093979268)
00:00.981: Song::LoadFromSMFile(Cache//Songs/2072895647)
00:00.982: Song::LoadFromSMFile(Cache//Songs/4044554974)
00:00.983: Song::LoadFromSMFile(Cache//Songs/2680652983)
00:00.984: Song::LoadFromSMFile(Cache//Songs/816252504)
00:00.985: Song::LoadFromSMFile(Cache//Songs/3549722414)
00:00.986: Song::LoadFromSMFile(Cache//Songs/883896767)
00:00.986: Song::LoadFromSMFile(Cache//Songs/2014746242)
00:00.987: Loaded 25 songs from "Songs/Mods Boot Camp"
00:00.987: Group banner for 'Mods Boot Camp' is '(none)'.
00:00.988: Attempting to load 28 songs from "Songs/Mods Boot Camp 2"
00:00.988: Song::LoadFromSMFile(Cache//Songs/1412656392)
00:00.990: Song::LoadFromSMFile(Cache//Songs/4183379676)
00:00.991: Song::LoadFromSMFile(Cache//Songs/3238571009)
00:00.991: Song::LoadFromSMFile(Cache//Songs/2790257696)
00:00.992: Song::LoadFromSMFile(Cache//Songs/2887725477)
00:00.993: Song::LoadFromSMFile(Cache//Songs/4268414929)
00:00.994: Song::LoadFromSMFile(Cache//Songs/1083600359)
00:00.995: Song::LoadFromSMFile(Cache//Songs/3188014528)
00:00.996: Song::LoadFromSMFile(Cache//Songs/781494011)
00:00.997: Song::LoadFromSMFile(Cache//Songs/2825881848)
00:00.998: Song::LoadFromSMFile(Cache//Songs/2068380530)
00:00.999: Song::LoadFromSMFile(Cache//Songs/2941677185)
00:01.000: Song::LoadFromSMFile(Cache//Songs/312784277)
00:01.001: Song::LoadFromSMFile(Cache//Songs/733184735)
00:01.002: Song::LoadFromSMFile(Cache//Songs/3077685759)
00:01.003: Song::LoadFromSMFile(Cache//Songs/839668050)
00:01.004: Song::LoadFromSMFile(Cache//Songs/4002224470)
00:01.005: Song::LoadFromSMFile(Cache//Songs/2017285584)
00:01.006: Song::LoadFromSMFile(Cache//Songs/2739072065)
00:01.007: Song::LoadFromSMFile(Cache//Songs/1861462340)
00:01.008: Song::LoadFromSMFile(Cache//Songs/2585076586)
00:01.010: Song::LoadFromSMFile(Cache//Songs/1568656068)
00:01.012: Song::LoadFromSMFile(Cache//Songs/547647123)
00:01.013: Song::LoadFromSMFile(Cache//Songs/691005904)
00:01.015: Song::LoadFromSMFile(Cache//Songs/1150011034)
00:01.016: Song::LoadFromSMFile(Cache//Songs/343910448)
00:01.017: Song::LoadFromSMFile(Cache//Songs/3332547897)
00:01.018: Song::LoadFromSMFile(Cache//Songs/3654242411)
00:01.018: Loaded 28 songs from "Songs/Mods Boot Camp 2"
00:01.018: Group banner for 'Mods Boot Camp 2' is '(none)'.
00:01.018: Found 53 songs in 0.080353 seconds.
00:01.018: Loading courses.
00:01.019: Starting thread: Worker thread (MemoryCardWorker)
00:01.020: MemoryCardDriverThreaded_Windows::GetUSBStorageDevices
00:01.020: C:
00:01.020: MemoryCardOsMountPointP1: 
00:01.020: MemoryCardOsMountPointP2: 
00:01.020: not DRIVE_REMOVABLE
00:01.020: E:
00:01.020: MemoryCardOsMountPointP1: 
00:01.020: MemoryCardOsMountPointP2: 
00:01.025: RageSound::LoadSound( '/Themes/SIMPLY LOVE (NotITG ver)/Sounds/MemoryCardManager ready.ogg', 1 )
00:01.028: not TestReady
00:01.028: F:
00:01.028: MemoryCardOsMountPointP1: 
00:01.028: MemoryCardOsMountPointP2: 
00:01.036: not TestReady
00:01.036: G:
00:01.036: MemoryCardOsMountPointP1: 
00:01.036: MemoryCardOsMountPointP2: 
00:01.044: not TestReady
00:01.044: H:
00:01.044: MemoryCardOsMountPointP1: 
00:01.044: MemoryCardOsMountPointP2: 
00:01.052: not TestReady
00:01.052: I:
00:01.052: MemoryCardOsMountPointP1: 
00:01.052: MemoryCardOsMountPointP2: 
00:01.060: not TestReady
00:01.060: J:
00:01.060: MemoryCardOsMountPointP1: 
00:01.060: MemoryCardOsMountPointP2: 
00:01.060: not DRIVE_REMOVABLE
00:01.162: RageSound::LoadSound( '/Themes/SIMPLY LOVE (NotITG ver)/Sounds/MemoryCardManager error.ogg', 1 )
00:01.203: RageSound::LoadSound( '/Themes/SIMPLY LOVE (NotITG ver)/Sounds/MemoryCardManager error.ogg', 1 )
00:01.214: RageSound::LoadSound( '/Themes/SIMPLY LOVE (NotITG ver)/Sounds/MemoryCardManager disconnect.ogg', 1 )
00:01.244: Starting thread: Worker thread (/@mc1int/)
00:01.245: Starting thread: Worker thread (/@mc2int/)
00:01.260: ProfileManager::ProfileManager()
00:01.260: Profile::LoadAllFromDir( Data/MachineProfile/ )
00:01.260: Starting timer for LoadEditableDataFromDir_Editable
00:01.261: Time for LoadEditableDataFromDir_Editable: 0.0007
00:01.261: Starting timer for LoadEditableDataFromDir_Extra
00:01.261: Time for LoadEditableDataFromDir_Extra: 0.0003
00:01.261: LoadEditableDataFromDir() took 0.00 seconds
00:01.261: Loading Data/MachineProfile/Stats.xml
00:01.261: xml.LoadFromFile() took 0.00 seconds
00:01.261: Done.
00:01.261: Starting timer for LoadStatsXmlFromNode
00:01.261: Starting timer for LoadGeneralDataFromNode
00:01.261: Time for LoadGeneralDataFromNode: 0.0001
00:01.261: Starting timer for LoadSongScoresFromNode
00:01.261: Time for LoadSongScoresFromNode: 0.0000
00:01.262: Starting timer for LoadCategoryScoresFromNode
00:01.262: Time for LoadCategoryScoresFromNode: 0.0000
00:01.262: Starting timer for LoadScreenshotDataFromNode
00:01.262: Time for LoadScreenshotDataFromNode: 0.0000
00:01.262: Starting timer for LoadRecentSongScoresFromNode
00:01.262: Time for LoadRecentSongScoresFromNode: 0.0000
00:01.262: Time for LoadStatsXmlFromNode: 0.0002
00:01.262: UnlockManager::Load()
00:01.290: Writing Data/Catalog.xml ...
00:01.417: Done.
00:01.441: Last seen video driver: NVIDIA GeForce GTX 1060
00:01.441: Video renderers: 'opengl'
00:01.441: RageDisplay_OGL::RageDisplay_OGL()
00:01.505: SetScreenMode ...
00:01.828: Reset: pixel format changing
/////////////////////////////////////////
00:01.836: WARNING: Invalid format: Mode: software 32 (888) 16 depth 8 stencil 64 accum 
/////////////////////////////////////////
00:01.838: Paletted textures disabled: glGetTexLevelParameteriv(GL_TEXTURE_INDEX_SIZE_EXT) failed (GL_INVALID_ENUM).
00:01.838: GL_UNSIGNED_SHORT_1_5_5_5_REV failed (GL_INVALID_ENUM), disabled
00:01.840: OGL Vendor: Microsoft Corporation
00:01.840: OGL Renderer: GDI Generic
00:01.840: OGL Version: 1.1.0
00:01.840: OGL Max texture size: 1024
00:01.841: OGL Texture units: 1
00:01.841: OGL Extensions: GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
00:01.841: GLU Version: 1.2.2.0 Microsoft Corporation
00:01.872: 
00:01.872: //////////////////////////////////////////////////////
00:01.872: Exception: There was an error while initializing your video card.
00:01.872: 
00:01.872:    PLEASE DO NOT FILE THIS ERROR AS A BUG!
00:01.872: 
00:01.872: Video Driver: opengl
00:01.872: 
00:01.872: Initializing OpenGL...
00:01.872: Your system is reporting that OpenGL hardware acceleration is not available.  Please obtain an updated driver from your video card manufacturer.
00:01.872: 
00:01.872: 
00:01.872: //////////////////////////////////////////////////////
00:01.872: 
00:01.872: ShutDownGame
00:01.872: Shutting down mixer thread ...
00:01.887: Mixer thread shut down.
00:01.893: Shutting down decode thread ...
00:01.907: Decode thread shut down.
00:01.907: Mixing 7409.145833 ahead in 48 Mix() calls

**Comment by Jousway** [comment]
00:01.840: OGL Vendor: Microsoft Corporation
00:01.840: OGL Renderer: GDI Generic
00:01.840: OGL Version: 1.1.0
00:01.840: OGL Max texture size: 1024
00:01.841: OGL Texture units: 1
00:01.841: OGL Extensions: GL_WIN_swap_hint GL_EXT_bgra GL_EXT_paletted_texture
00:01.841: GLU Version: 1.2.2.0 Microsoft Corporation

microsoft does not give the latest driver, you might want to check the intel site
